CONVERT_TO = helios
ENCODER_MAP_ENABLE = yes
LEADER_ENABLE = yes
TAP_DANCE_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c

MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
